create table operation_group_history(
    group_id varchar,
    action varchar,
    data jsonb,
    user_id varchar,
    date timestamp without time zone,
    automatic bool
);

insert into operation_group_history
select 
group_id, 'create' as action, 
jsonb_build_object(
    'PackageId', package_id,
    'Version', version,
    'Revision', revision,
    'ApiType', api_type,
    'GroupName', group_name,
    'GroupId', group_id,
    'Description', coalesce(description, ''),
    'Autogenerated', coalesce(autogenerated, false),
    'TemplateChecksum', coalesce(template_checksum, ''),
    'TemplateFilename', coalesce(template_filename, '')) as data, 
'unknown' as user_id, now() as date, true as automatic
from operation_group where autogenerated = false;
