create table operations_group 
(
    package_id varchar not null,
    version varchar not null,
    revision integer not null,
    group_name varchar not null,
    api_type varchar not null,
    operation_ids varchar array null,
    autogenerated boolean not null,
    PRIMARY KEY(package_id, version, revision, group_name, api_type)
);

ALTER TABLE operations_group ADD CONSTRAINT "FK_published_version"
    FOREIGN KEY (package_id, version, revision) REFERENCES published_version (package_id, version, revision) ON DELETE Cascade ON UPDATE Cascade;

alter table package_group add column rest_grouping_prefix varchar default null;