alter table build drop constraint if exists build_package_group_id_fk;

alter table published_data drop constraint if exists published_data_package_group_id_fk;

alter table published_sources_data drop constraint if exists published_sources_data_package_group_id_fk ;

alter table shared_url_info drop constraint if exists shared_url_info_package_group_id_fk;

alter table published_version_open_count drop constraint if exists published_version_open_count_package_group_id_fk;

alter table activity_tracking drop constraint if exists activity_tracking_package_group_id_fk;

alter table public.migrated_version drop constraint if exists migrated_version_package_group_id_fk;

alter table published_document_open_count drop constraint if exists published_document_open_count_package_group_id_fk;

alter table operation_comparison drop constraint if exists operation_comparison_package_group_id_fk;

alter table ts_published_data_errors drop constraint if exists ts_published_data_errors_package_group_id_fk;

alter table ts_published_data_custom_split drop constraint if exists ts_published_data_custom_split_package_group_id_fk;
