drop table operations_group;

create table operation_group 
(
    package_id varchar not null,
    version varchar not null,
    revision integer not null,
    api_type varchar not null,
    group_name varchar not null,
    autogenerated boolean not null,
    group_id varchar not null,
    description varchar null,
    PRIMARY KEY(package_id, version, revision, api_type, group_name),
    UNIQUE(group_id)
);

create table grouped_operation
(
    group_id varchar not null,
    package_id varchar not null,
    version varchar not null,
    revision integer not null,
    operation_id varchar not null
);

ALTER TABLE grouped_operation ADD CONSTRAINT "FK_operation_group"
    FOREIGN KEY (group_id) REFERENCES operation_group (group_id) ON DELETE Cascade ON UPDATE Cascade;

ALTER TABLE grouped_operation ADD CONSTRAINT "FK_operation"
    FOREIGN KEY (package_id, version, revision, operation_id) REFERENCES operation (package_id, version, revision, operation_id) ON DELETE Cascade ON UPDATE Cascade;

ALTER TABLE operation_group ADD CONSTRAINT "FK_published_version"
    FOREIGN KEY (package_id, version, revision) REFERENCES published_version (package_id, version, revision) ON DELETE Cascade ON UPDATE Cascade;
