name: my test
on:
  delete:
    branches:
      - "**"  

jobs:
  cleanup:
    runs-on: ubuntu-latest

    env:
      REF_NAME: ${{ github.ref }}
      PREFIX: "timestamp"
      THRESHOLD_DAYS: "0"           
      INCLUDED_TAGS: ""             
      EXCLUDED_TAGS: ""     
      DRY_RUN: "true"               
      DEBUG: "false"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Tag
        id: prepare_tag
        run: |
          TAG=$(echo ${REF_NAME} | sed 's@refs/tags/@@;s@refs/heads/@@;s@refs/pull/@pull/@;s@^develop$@dev@;s@^release$@next@;s@/@-@g;')
          echo "TAG=$TAG"
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Prepare Tags To Delete
        id: prepare_tags_delete
        run: |
          TAGS_TO_DELETE=$(echo "${PREFIX}-*-${TAG}, $INCLUDED_TAGS" | sed 's/, $//)
          echo "TAGS_TO_DELETE=$TAGS_TO_DELETE"
          echo "TAGS_TO_DELETE=$TAGS_TO_DELETE" >> $GITHUB_OUTPUT

      - name: "Summary"
        run: |
          echo "**Event**: ${{ github.event_name }}"
          echo "**Actor**: ${{ github.actor }}"
          echo "**Threshold days**: ${{ $THRESHOLD_DAYS }}"
          echo "**Included tags**:  ${{ TAGS_TO_DELETE }}"
          echo "**Excluded tags**: ${{ $EXCLUDED_TAGS }}"
          echo "**Dry-run**: ${{ $DRY_RUN }}"
          echo "**Debug**: ${{ $DEBUG }}"

      - name: Run Container Package Cleanup Action
        uses: raa1618033/qubership-workflow-hub/actions/container-package-cleanup@main
        with:
          threshold-days: ${{ $THRESHOLD_DAYS }}
          included-tags: ${{ TAGS_TO_DELETE }}
          excluded-tags: ${{ $EXCLUDED_TAGS }}
          dry-run: ${{ $DRY_RUN }}
          debug: ${{ $DEBUG }}
        env:
          PACKAGE_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
