name: my test
on:
  delete:
    branches:
      - "**"  
env:
  REF_NAME: ${{ github.ref }}
  PREFIX: "timestamp"
  THRESHOLD_DAYS: "0"           
  INCLUDED_TAGS: ""             
  EXCLUDED_TAGS: ""     
  DRY_RUN: "true"               
  DEBUG: "false"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Handle branch deletion
        if: github.event.ref_type == 'branch'
        run: |
          echo "The deleted branch is: ${{ github.event.ref }}"

